name: validates pull requests to master

on:
  pull_request:
    branches:
      - master

jobs:
  commitlint:
    name: Check commit messages are valid
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
  test:
    name: Check unit tests are valid
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x, 13.x]
        react: [16.9.x]
        react-native-svg: [7.x, 8.x, 9.x, 10.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: yarn install and test
        run: |
          yarn install
          yarn upgrade react@${{ matrix.react }} react-dom@${{ matrix.react }} react-test-renderer@${{ matrix.react }} react-native-svg@${{ matrix.react-native-svg }}
          yarn list react react-dom react-test-renderer react-native-svg
          yarn test
