nodeLinker: node-modules
nmHoistingLimits: none
enableGlobalCache: true
yarnPath: '.yarn/releases/yarn-3.0.2.cjs'

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: 'EDDEC17D-8666-42BA-BCB2-F1DEE22F9AD2'
