name: Packages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
        with:
          token: ${{ secrets.BREEFFYBOT_TOKEN }}
      - run: yarn install --immutable
      - name: Build packages
        run: yarn build
