name: test code, create and publish release

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run jest tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x, 13.x]
        react: [16.9.x]
        react-native-svg: [7.x, 8.x, 9.x, 10.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: yarn install and test
        run: |
          yarn install
          yarn upgrade react@${{ matrix.react }} react-dom@${{ matrix.react }} react-test-renderer@${{ matrix.react }} react-native-svg@${{ matrix.react-native-svg }}
          yarn list react react-dom react-test-renderer react-native-svg
          yarn test
  release:
    name: Create and publish package
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Show current node version
        run: node --version
      - name: Install dependencies and local binaries
        if: success()
        run: yarn install
      - name: Generate js, d.ts files in dist directory
        if: success()
        run: yarn dist
      - name: Generate local gzipped package
        if: success()
        run: yarn pack
      - name: Show name of gzipped package
        if: success()
        run: ls breeffy-react-native-svg-icons-v*.tgz
      - name: Run semantic-release to prepare and publish release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: success()
        run: npx semantic-release
