name: Run tests and prepare releases

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run jest tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x, 13.x]
        react: [16.9.x]
        react-native-svg: [7.x, 8.x, 9.x, 10.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: yarn install and test
        run: |
          yarn install
          yarn upgrade react@${{ matrix.react }} react-dom@${{ matrix.react }} react-test-renderer@${{ matrix.react }} react-native-svg@${{ matrix.react-native-svg }}
          yarn list react react-dom react-test-renderer react-native-svg
          yarn test
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Run semantic-release to prepare release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
